### ISSUE TITLE
Fails to build with cython-0.23.beta1

### ISSUE THREAD

**Issue by jbeich** [freenas/py-libzfs#7]
I'm thinking of updating lang/cython port once 0.23 is out of beta cycle and devel/py-libzfs is one of the few broken with the new version. Trying git master (9293c6c currently) doesn't help. Only one warning is gone.

Dropping `ctypedef` before `enum zfs_error` or the whole definition seems to help. For one, cython-0.22.1 doesn't put unused types like zfs_error in libzfs.c at all.

```
libzfs.c:1356:59: error: must use 'enum' tag to refer to type 'zfs_error'
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_zfs_error(zfs_error value);
                                                          ^
                                                          enum
libzfs.c:36496:59: error: must use 'enum' tag to refer to type 'zfs_error'
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_zfs_error(zfs_error value) {
                                                          ^
                                                          enum
libzfs.c:36497:11: error: must use 'enum' tag to refer to type 'zfs_error'
    const zfs_error neg_one = (zfs_error) -1, const_zero = (zfs_error) 0;
          ^
          enum
libzfs.c:36497:32: error: use of undeclared identifier 'zfs_error'; did you mean
      '__error'?
    const zfs_error neg_one = (zfs_error) -1, const_zero = (zfs_error) 0;
                               ^~~~~~~~~
                               __error
/usr/include/sys/errno.h:44:7: note: '__error' declared here
int *   __error(void);
        ^
libzfs.c:36497:21: warning: incompatible pointer to integer conversion initializing
      'const enum zfs_error' with an expression of type 'int *(*)(void)'
      [-Wint-conversion]
    const zfs_error neg_one = (zfs_error) -1, const_zero = (zfs_error) 0;
                    ^         ~~~~~~~~~~~~~~
libzfs.c:36497:61: error: use of undeclared identifier 'zfs_error'; did you mean
      '__error'?
    const zfs_error neg_one = (zfs_error) -1, const_zero = (zfs_error) 0;
                                                            ^~~~~~~~~
                                                            __error
/usr/include/sys/errno.h:44:7: note: '__error' declared here
int *   __error(void);
        ^
libzfs.c:36497:47: warning: incompatible pointer to integer conversion initializing
      'const enum zfs_error' with an expression of type 'int *(void)'
      [-Wint-conversion]
    const zfs_error neg_one = (zfs_error) -1, const_zero = (zfs_error) 0;
                                              ^            ~~~~~~~~~~~
libzfs.c:36497:71: error: expected ';' at end of declaration
    const zfs_error neg_one = (zfs_error) -1, const_zero = (zfs_error) 0;
                                                                      ^
                                                                      ;
libzfs.c:36500:20: error: use of undeclared identifier 'zfs_error'; did you mean
      '__error'?
        if (sizeof(zfs_error) < sizeof(long)) {
                   ^~~~~~~~~
                   __error
/usr/include/sys/errno.h:44:7: note: '__error' declared here
int *   __error(void);
        ^
libzfs.c:36502:27: error: use of undeclared identifier 'zfs_error'; did you mean
      '__error'?
        } else if (sizeof(zfs_error) <= sizeof(unsigned long)) {
                          ^~~~~~~~~
                          __error
/usr/include/sys/errno.h:44:7: note: '__error' declared here
int *   __error(void);
        ^
libzfs.c:36504:27: error: use of undeclared identifier 'zfs_error'; did you mean
      '__error'?
        } else if (sizeof(zfs_error) <= sizeof(unsigned PY_LONG_LONG)) {
                          ^~~~~~~~~
                          __error
/usr/include/sys/errno.h:44:7: note: '__error' declared here
int *   __error(void);
        ^
libzfs.c:36508:20: error: use of undeclared identifier 'zfs_error'; did you mean
      '__error'?
        if (sizeof(zfs_error) <= sizeof(long)) {
                   ^~~~~~~~~
                   __error
/usr/include/sys/errno.h:44:7: note: '__error' declared here
int *   __error(void);
        ^
libzfs.c:36510:27: error: use of undeclared identifier 'zfs_error'; did you mean
      '__error'?
        } else if (sizeof(zfs_error) <= sizeof(PY_LONG_LONG)) {
                          ^~~~~~~~~
                          __error
/usr/include/sys/errno.h:44:7: note: '__error' declared here
int *   __error(void);
        ^
libzfs.c:36517:52: error: use of undeclared identifier 'zfs_error'; did you mean
      '__error'?
        return _PyLong_FromByteArray(bytes, sizeof(zfs_error),
                                                   ^~~~~~~~~
                                                   __error
/usr/include/sys/errno.h:44:7: note: '__error' declared here
int *   __error(void);
        ^
2 warnings and 12 errors generated.
```
